### ISSUE TITLE
A question about the behavior of a function

### ISSUE THREAD

**Issue by haochenpan** [Nsupyq/idempotent-serverless-functions#1]
Hi @Nsupyq,

In [examples-657](https://github.com/serverless/examples/issues/657), you proposed to replace `dynamoDbClient.put` with `dynamoDbClient.transactWrite` because two user creation/update requests submitted in a short internal with the same userID should be recognized as duplicated requests, and thus the user should expect idempotent responses. 

The idempotency key in your [attempted fix](https://github.com/Nsupyq/idempotent-serverless-functions/blob/9d8e03112db18bb80069c69629815f2446b2545f/idempotent-aws-node-express-dynamodb-api/handler.js#L61) is `awsRequestId`. If a client manually submits two requests with the same userID but different user names in a short interval, will that generate two `awsRequestId`'s? If so, how does such an attempted fix improve the code's behavior (I guess two requests will succeed eventually, so the user first sees the userID is paired with a name and then paired with another name)?

I am learning AWS idempotency features, and please correct me if I am wrong. 
Thank you and happy holidays,

Haochen

**Comment by Nsupyq** [comment]
Hi @haochenpan,

Thanks for your questions.

First, the `awsRequestId` is generated by AWS Lambda and is unique for every request. Therefore, the `awsRequestId`s generated for two requests which are sent in a short interval are also different.

Second, the behavior described in your issue is legal and idempotence does not improve it. This is because idempotence means all behavior produced under crash and retry can also be produced without crash and retry. In this case, without crash and retry, the user can still first see the userID is paired with a name and then paired with another name. Therefore, the behavior is legal and the code is idempotent. The real problem of the original non-idempotent code is that the original code may change the name for any times. However, when only two instances are changing the name and no crash happens, the name should only be modified for twice instead of any times.

Happy 2022 !

**Comment by haochenpan** [comment]
Hi @Nsupyq,

Thank you for your detailed explanation! I found a [definition of idempotency](https://aws.amazon.com/builders-library/making-retries-safe-with-idempotent-APIs/) that may suit our discussion: A serverless function is idempotent if “the result of the call happens only once.” 


I wonder if the following is what you mean: 

When there are two concurrent `dynamoDbClient.transactWrite` calls (each associated with a unique `awsRequestId`) been executed on unhealthy machines, the legal&expected behavior is the user may perceive the results of the calls one after another; this behavior satisfies the idempotency definition above. However, when two concurrent `dynamoDbClient.put` calls have been executed on unhealthy machines, the user may see the name -- associated with an `id` --  changed from `name1` to `name2` and then back to `name1` under retries. This potential behavior implies the function violates the idempotency defined above.

Also, I wonder do you happen to have some good materials (websites, book, etc.) for learning serverless idempotency? : ) I still want to learn more about this aspect.

Happy weekend,
Haochen

**Comment by Nsupyq** [comment]
You are right!
The paper [Formal Foundations of Serverless Computing](https://arxiv.org/pdf/1902.05870.pdf) has something about idempotency.

**Comment by haochenpan** [comment]
Thanks for the resource! I will check it out!
